language: node_js
cache: yarn
node_js: "8"
script: echo "Deploy!!"
install:
  - yarn global add firebase-tools
  - yarn
after_success:
  - yarn run build
  - firebase --project vitordino-todo --token $FIREBASE_TOKEN deploy --public build
